apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
type: Opaque
stringData:
  rootPassword: {{ .Values.auth.rootPassword | quote }}
  password: {{ .Values.auth.password | quote }}
