spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: counters-api
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/counters
    username: ${DB_USERNAME:counters}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/counters}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/counters/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
