/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/counters': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCounters']
    put?: never
    post: operations['createCounter']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/counters/{id}/reset': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['resetCounter']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/counters/{id}/increment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['incrementCounter']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/counters/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCounter']
    put?: never
    post?: never
    delete: operations['deleteCounter']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CreateCounterRequest: {
      label: string
      /** Format: int32 */
      step: number
      /** Format: int32 */
      start?: number
    }
    ValidationProblem: {
      type?: string
      title: string
      /** Format: int32 */
      status: number
      detail: string
      /** Format: uri-reference */
      instance: string
      errors: {
        [key: string]: string
      }
    }
    CounterResponse: {
      /** Format: uuid */
      id: string
      label: string
      /** Format: int32 */
      step: number
      /** Format: int32 */
      start: number
      /** Format: int32 */
      count: number
    }
    Problem: {
      type?: string
      title: string
      /** Format: int32 */
      status: number
      detail: string
      /** Format: uri-reference */
      instance: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getCounters: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CounterResponse'][]
        }
      }
    }
  }
  createCounter: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCounterRequest']
      }
    }
    responses: {
      /** @description Counter created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CounterResponse']
        }
      }
      /** @description Counter creation failed */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ValidationProblem']
        }
      }
    }
  }
  resetCounter: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The counter */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CounterResponse']
        }
      }
      /** @description Counter not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  incrementCounter: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The counter */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CounterResponse']
        }
      }
      /** @description Counter not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  getCounter: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The counter */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CounterResponse']
        }
      }
      /** @description Counter not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
  deleteCounter: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Counter deleted */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Counter not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['Problem']
        }
      }
    }
  }
}
