apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
      {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminPassword: {{ required "auth.admin.password must be set (values.local.yaml)" .Values.auth.admin.password | quote }}
